name: Run Great Expectations

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run dbt Gold Models"]
    types: [completed]

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  run-ge:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Check Databricks auth
        run: databricks current-user me
      - name: Run validation job
        run: databricks bundle run approvalmax_great_expectations_serverless -t dev

